### ISSUE TITLE
Nuget.org package

### ISSUE THREAD

**Issue by yetanotherchris** [xmlunit/xmlunit.net#15]
I've uploaded the xmlunit-core nuget package to nuget.org so I can reference it in a project instead of having to use a lib folder for the dll.

It's sat here: https://www.nuget.org/packages/xmlunit-core/2.0.0-alpha-01
and here: https://www.nuget.org/packages/xmlunit-constraints/2.0.0-alpha-01

I can transfer ownership of the nuget.org ID/package if you like, or if you have no plans to put it onto nuget.org I can change the project ID on nuget.org, either way it's probably best you own the original as I won't be updating it using a CI or automated build script so it could get out of date..

**Comment by bodewig** [comment]
See #13 and #5 - yes, we do want to publish nuget packages ourselves :-)

It would be great if you could help us integrating package creation into the build process and transfer ownership after that.

Many thanks!

**Comment by yetanotherchris** [comment]
I got the beginnings of a travis.yml file working here:

https://github.com/yetanotherchris/xmlunit.net/blob/master/.travis.yml

Unfortunately when I try to `nuget pack` it says this feature isn't supported. It also shows your API key in the Travis command log which isn't good, I had it in my repository settings but it looks like hiding sensitive environment variables is a bit of work.

Maybe you could get your Appveyor to do these steps after the build? It's really just a case of doing:

- nuget pack ./src/main/net-core/XMLUnit.Core.csproj
- nuget pack ./src/main/net-constraints/XMLUnit.Constraints.csproj
- nuget push *.nupkg -ApiKey {your-api-key-from-nuget.org}

**Comment by bodewig** [comment]
Thanks.

xbuild should already be running the unit test (I've added some crude exec based solution directly into the project files of the tests).

Appveyor offers Nuget package deployment and even hosting themselves, I'll look into that a little bit deeper during the weekend.

I was looking for a solution that created the packages but doesn't publish them during the build process, I'm happy with publishing things manually.  There already are nuspec files inside the nuget subdir of xmlunit.net and I'd like to reuse them (we used to create packages with the NAnt build).

**Comment by bodewig** [comment]
appveyor now builds nuget packages, for example https://ci.appveyor.com/project/bodewig/xmlunit-net/build/job/oyj411yv8x5hs2q2/artifacts

I think the contents are pretty much what one would expect, but please verify.

I'll need to figure out how to make the feed work properly, but the packages are there.  Once the feed is working I'll link to them as CI SNAPSHOT packages until I'm ready to cut a real alpha release (which shoudn't be too far away).

The "real" releases will be published to nuger.org.

**Comment by yetanotherchris** [comment]
Looks good to me, I can delete the nuget.org id whenever it's ready for the official feed.

**Comment by bodewig** [comment]
Thank you. I'll ping you when I'm ready to prepare a real alpha.

**Comment by bodewig** [comment]
PING :-)

I've got a pretty clear idea of how to attack the last remaining issue and plan to cut our first official alpha release in the next week or two.

**Comment by yetanotherchris** [comment]
I've transferred it across, feel free to remove me from the nuget packages

**Comment by bodewig** [comment]
Thanks, got it.  I don't see any reason to remove you.

**Comment by bodewig** [comment]
OK, alpha-02 is up.

I've just realized after uploading the packages that our nuspec files used different ids than you have used.  Even worse, ours are inconsistent.  In the future I'll use XMLUnit.Core and XMLUnit.Constraints with capital M and L.

I'm not sure whether there is a way to merge different package ids.

**Comment by bodewig** [comment]
all three packages (Constraints are available for NUnit2 and NUnit3) seem to be correct now.
