### ISSUE TITLE
Create and clarify milestones and roadmap

### ISSUE THREAD

**Issue by jawn** [xmlunit/xmlunit.net#17]
Hello,

Thanks for this useful project!

If I see it correctly, the project is currently in alpha state. What needs to happen to get it to beta and release states?

Greetings,

Bernard

**Comment by bodewig** [comment]
For beta state I'd like to see issues xmlunit/xmlunit#2 and xmlunit/xmlunit#26 fixed so we don't need to break the API after the beta.  I've got a couple of ideas and currently lack the time implementing it myself.

**Comment by jawn** [comment]
Thanks for the quick feedback.

**Comment by bodewig** [comment]
Right now all we need is sufficient testing of alpha-02 and based on feedback there'll either be a alpha-03 or a real release - I don't think a beta is warranted.

**Comment by jawn** [comment]
THanks for the clarification.
