### ISSUE TITLE
Assembly version conflict

### ISSUE THREAD

**Issue by GKotfis** [xmlunit/xmlunit.net#24]
Project type: C# library
Target Framework: 4.6
NUnit: 3.0.1 (3.0.5813.39031)
XMLUnit: 2.5.1

Similar issue: #20 

App.config assembly redirect:
```xml
<dependentAssembly>
    <assemblyIdentity name="nunit.framework" publicKeyToken="2638cd05610744eb" culture="neutral"/>
    <bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="3.0.5813.39031"/>
</dependentAssembly>
```

Error message:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'xmlunit-nunit3-constraints' with identity 'xmlunit-nunit3-constraints, Version=2.5.1.121, Culture=neutral, PublicKeyToken=e7d7e3088fd452f6' uses 'nunit.framework, Version=3.0.5813.39033, Culture=neutral, PublicKeyToken=2638cd05610744eb' which has a higher version than referenced assembly 'nunit.framework' with identity 'nunit.framework, Version=3.0.5813.39031, Culture=neutral, PublicKeyToken=2638cd05610744eb'	SDM.HPCPost.Test
`

Despite the indication assembly redirect I still have this error. What else can I try? I tried unloading, rebuilding project - some tricks around Visual Studio but without effect. Unfortunately upgrading Nunit version it's not an option for now.

**Comment by bodewig** [comment]
I've added the "help wanted" label as I'm afraid I don't really have any solution myself.

Rather than trying to "downgrade" NUnit to 3.0.5813.39031 would it work if you "upgraded" from that version to 3.0.5813.39033? I.e. you use the .NET 2.0 assembly of NUnit 3.0.1 rather than the .NET 4.5 assembly?

**Comment by bodewig** [comment]
OK, thanks for the update.
