### ISSUE TITLE
Wrong Constraint resolve

### ISSUE THREAD

**Issue by GKotfis** [xmlunit/xmlunit.net#25]
I think there is a problem with resolving constraint. Especially 'Not' constraints. Following test failed with message:
 `XML with XPath root/node  Expected: <empty> But was:  "someValue"`. 
`
XML with XPath root/node  Expected string length 3 but was 9. Strings differ at index 0.
  Expected: "ups"
  But was:  "someValue"
  -----------^
`

It should be `Expected:  <not empty>` for the first assertions and pass for second.

```csharp
[Test]
public void XPathTest()
{
    var xml = @"<root><node>someValue</node></root>";

    Assert.That(xml, EvaluateXPathConstraint.HasXPath("root/node", Is.Not.Empty));
    Assert.That(xml, EvaluateXPathConstraint.HasXPath("root/node", Is.Not.EqualTo("ups")));
}
```

I've made a simple change by adding `Resolve()` to valueConstraint. In this cases, it helps. I'm not familiar with custom constraints in NUnit and don't know if it's appropriate solution that cover all cases.

```csharp
public static EvaluateXPathConstraint HasXPath(string xPath, IConstraint valueConstraint)
{
    return new EvaluateXPathConstraint(xPath, valueConstraint.Resolve());
}
```

**Comment by bodewig** [comment]
To be honest it's been some time since I last looked into writing constraints. There have already been bugs when the constraints have been combined with others - see https://github.com/xmlunit/xmlunit.net/commit/95b7519488e1bc7434ec849f641aa4411e711b47 for example.

It may take a few days before I find time to look into it, many thanks for the simple test case.

**Comment by bodewig** [comment]
Many thanks for the report. While writing the tests for this I discovered the messages where also misleading for all of the NUnit3 constraints (and some of the NUnit2 constraints) when they were negated.
