### ISSUE TITLE
bug in get xpath of node

### ISSUE THREAD

**Issue by deaknaew** [xmlunit/xmlunit.net#29]
it's have bug that will navigate to wrong child when apply node filter

in Org.XmlUnit.Diff
DOMDifferenceEngine
function
UnmatchedControlNodes
and
UnmatchedTestNodes

the problem is that NavigateToChild was passed by index of List<XmlNode> 
that was filtered out
it must get correct index before pass to NavigateToChild
 may be add something like
Array.IndexOf(testList[i].ParentNode.ChildNodes.Cast<XmlNode>().ToArray(),testList[i])

bug example

```
var aa= DiffBuilder.Compare("<Document><Section><Binding /><Binding /><Finding /><Finding /><Finding /><Finding /><Finding /><Finding /><Finding /></Section></Document>")
.WithTest("<Document><Section><Binding /><Binding /><Finding /><Finding /><Finding /><Finding /><Finding /><Finding /></Section></Document>")
.IgnoreWhitespace()
.WithNodeFilter(node =>  "Document,Section,Finding".Split(',').Contains(node.Name))
.WithNodeMatcher(new DefaultNodeMatcher(ElementSelectors.ByNameAndText)).Build();
```

**Comment by bodewig** [comment]
Sounds a lot like https://github.com/xmlunit/xmlunit/issues/156 that I fixed with https://github.com/xmlunit/xmlunit.net/commit/d9d6ae3258c285a8d8e043ecb0786f8a27983e8b for XMLUnit.NET 2.7.1.

So before I dig deeper into this, which version of XMLUnit.NET are you using?

**Comment by deaknaew** [comment]
I use 2.7.1 and also use lastest GitHub source to test

**Comment by bodewig** [comment]
Thanks, so this is a related but separate bug, that likely exists in the Java version as well.

**Comment by bodewig** [comment]
Thanks, this should be fixed in master now.
