### ISSUE TITLE
want to ignore sequence if child node have attribute

### ISSUE THREAD

**Issue by deaknaew** [xmlunit/xmlunit.net#30]
i want to ignore result that first childnode have difference index between control and test like

```
<Document>
      <a>a</a>
      <a b="a">a</a>
</Document>

<Document>
      <a b="a">a</a>
      <a>a</a>
</Document>

```
```
DiffBuilder.Compare("<Document><a>a</a><a b=\"a\">a</a></Document>").WithTest("<Document><a b=\"a\">a</a><a>a</a>></Document>")
                .IgnoreWhitespace().WithNodeMatcher(new DefaultNodeMatcher(ElementSelectors.ByName)).Build();
```
Not sure am i set NodeMatcher correct or not?

**Comment by bodewig** [comment]
You `ElementSelector` says "any a is good to be compared with any a" and so in your case the `a`s are compared in sequence.

If I understand your question correctly you want XMLUnit to compare the `a`s with the same `b` attribute to each other. This is what `ByNameAndAttributes("b")` would do.

**Comment by deaknaew** [comment]
i want result to be identical 
not sure if 
i have more attribute like
```
<Document>
      <a>a</a>
      <a b="a" c="a">a</a>
</Document>

<Document>
      <a b="a" c="a">a</a>
      <a>a</a>
</Document>
```

do i have more ByNameAndAttributes("b","c")

**Comment by bodewig** [comment]
you can list them all, or you can use `ByNameAndAllAttributes`.

After this the result will be `SIMILAR` unless you also provide a `DifferenceEvaluator` that downgrades the `CHILD_NODELIST_SEQUENCE` differences. Here `chain`ing the `Default` `DifferenceEvaluator` with `DowngradeDifferencesToEqual` can help.

**Comment by deaknaew** [comment]
Everything now ok, thank you.

**Comment by deaknaew** [comment]
i also use WithAttributeFilter not sure
ByNameAndAllAttributes it's must have to exclude Attribute that was filtered out by WithAttributeFilter or not?

and if not how can i conditional ByNameAndAttributes to filter in NodeMatcher

**Comment by bodewig** [comment]
I don't think `ByNameAndAllAttriutes` takes any attribute filter into account, they address different aspects and I have never thought through how they would interact. Attribute filters have been added long after element selectors.

It should be pretty easy to write an `ElementSelector` of your own that does what you *really* need.

**Comment by deaknaew** [comment]
Thank you
