### ISSUE TITLE
Release files

### ISSUE THREAD

**Issue by nicostubi** [xmlunit/xmlunit.net#33]
Hello,

I am totally new to this package.

I have been able to successfully compare two XML files based on the following code:

`          Diff myDiff = DiffBuilder.Compare(Input.FromFile(expected)).WithTest(Input.FromFile(result)).Build();
            // assert 
            Assert.False(myDiff.HasDifferences(), myDiff.ToString());
`

In the Dispose() method of my test class, I want to get rid of the tested file.

`public void Dispose()
        {
            foreach (var testFile in testFiles)
            {
                File.Delete(testFile);
            }
        }`

I get the folllowing error:

The process cannot access the file 'C:\Projects\....xml' because it is being used by another process.

I see that DiffBuilder is not disposable. 

BR
Nicolas

**Comment by bodewig** [comment]
@nicostubi I've transferred the issue over here as the problem doesn't exist in the same way inside of the Java version - or if it does, I cannot fix it, as the code uses [Java's StreamSource](https://docs.oracle.com/javase/7/docs/api/javax/xml/transform/stream/StreamSource.html) and that doesn't provide access to the file it may have opened.

**Comment by bodewig** [comment]
I've changed `ISource` to extend `IDisposable`, this should enable you to release file handles without the workaround.
