### ISSUE TITLE
Ignoring the sequence of child nodes doesn't work

### ISSUE THREAD

**Issue by amonich** [xmlunit/xmlunit.net#34]
I am getting 4 differences in this piece of code. Although I hope to get that they are identical

```
var xml1 = "<A><B>1</B><C>2</C></A>";
var xml2 = "<A><C>2</C><B>1</B></A>";

var source1 = Input.FromString(xml1).Build();
var source2 = Input.FromString(xml2).Build();

var diff = DiffBuilder
	.Compare(source1)
	.WithTest(source2)
	.WithDifferenceEvaluator(DifferenceEvaluators.Chain(
		DifferenceEvaluators.Default,
		DifferenceEvaluators.DowngradeDifferencesToSimilar(ComparisonType.CHILD_NODELIST_SEQUENCE)))
	.CheckForSimilar()
	.Build();
```

**Comment by bodewig** [comment]
you are telling XMLUnit to downgrade the sequence differences to similar, you want `DowngradeDifferencesToEqual`.

**Comment by amonich** [comment]
I tried to replace `DowngradeDifferencesToSimilar` with `DowngradeDifferencesToEqual`, but got the same result.
I also tried replacing `CheckForSimilar` with `CheckForIdentical`, but I still get differences in these cases.

**Comment by bodewig** [comment]
The thing you are missing is an `ElementSelector` that ensures you match same-named elements to each other. See https://github.com/xmlunit/xmlunit.net/commit/0952ce92045a5b314aa14aa031eedeba56300490 for a passing testcase.
