### ISSUE TITLE
Permit XML definition of white space 

### ISSUE THREAD

**Issue by Arithmeticus** [xmlunit/xmlunit.net#39]
I am using XML Unit 2.9.2 within the context of a .NET 4.72 application.

The method `NormalizeWhitespace()` is keyed to the Unicode property `Zs`, which targets more than a dozen characters. But the [specifications for XML](https://www.w3.org/TR/xml11/#sec-common-syn) define white space as only four characters: x9, xA, xD, x20, and that's the basis for standard technologies in the XML stack (e.g., XPath).

I can see the utility for the current XML Unit approach to whitespace, but I’m in a position where I need to use the more restrictive official XML definition. Could XML Unit 2 and 3 be enhanced to allow users to choose between definitions of whitespace?

**Comment by bodewig** [comment]
this is now https://github.com/xmlunit/xmlunit.net/issues/39

**Comment by Arithmeticus** [comment]
Thanks. I had posted on the java section, because it looked like that's where the party was. I'll give your suggestions a try.

**Comment by Arithmeticus** [comment]
Preliminary note, before more substantive comments. I managed to get the new XmlWhitespaceStrippedSource() object to work. It was challenging, because of gaps in the documentation. Note dead link: http://www.xmlunit.org/api/net/master/Org.XmlUnit.Builder/Input.html (host page https://github.com/xmlunit/user-guide/wiki/Providing-Input-to-XMLUnit#inputbuilder). 

I see https://www.xmlunit.org/api/net/2.9.2/Org.XmlUnit.Input/index.html but the documentation there seems incomplete. 

In the end I got it to work, but it took more time than I would have liked, and for anyone else trying to get their code to work, here's my approach:
```
string pathA = "D:\\bugs\\28724\\space_test_a.xml";
string pathB = "D:\\bugs\\28724\\space_test_b.xml";
ISource Benchmark = Input.FromFile(pathB).Build();
XmlWhitespaceStrippedSource BenchmarkStripped = new XmlWhitespaceStrippedSource(Benchmark);
ISource Test = Input.FromFile(pathA).Build();
XmlWhitespaceStrippedSource TestStripped = new XmlWhitespaceStrippedSource(Test);
Diff xmlDiffBuilder;
xmlDiffBuilder = DiffBuilder.Compare(TestStripped).WithTest(BenchmarkStripped).Build();
```

The new object works as expected, even though that wasn't what I was hoping to get. See next post.

**Comment by Arithmeticus** [comment]
Before submitting the ticket I had avoided the modified flavors of `-Source` objects, primarily because documentation was confusing, and I wasn't certain what I was going to get loaded up. Therefore I was looking at post-build methods such as `NormalizeWhitespace()`, which doesn't permit the strict XML definition for whitespace. I think a `XmlNormalizeWhitespace()` counterpart method, analogous to the adjustment you've made here, would be helpful.

That said, in figuring out the new class, I learned to appreciate the input `-Source` variants. If you're happy with the approach taken with `XmlWhitespaceStrippedSource`, then `WhitespaceNormalizedSource` would also need a `XmlWhitespaceNormalizedSource` counterpart. (That's the option I really wanted.)

For the purposes of documentation, it would be good to signal to users that the activity performed by `-StrippedSource` is a proper subset of the activity performed under `-NormalizedSource`. To some, "stripped" may sound harsher than "normalized" and imply a more drastic operation.

**Comment by bodewig** [comment]
Many thanks for the feedback @Arithmeticus . I consider the user's guide the primary documentation, so maybe https://github.com/xmlunit/user-guide/wiki/Providing-Input-to-XMLUnit would have been given better guidance - or not.

If you feel the documentation is not adequate please help us improving it. Sometimes it is difficult to know what is lacking from the docs when you are too familiar with the code.

I'll add `XmlWhitespaceNormalizedSource` and additional methods to the builder if this helps.

**Comment by bodewig** [comment]
OK, the builder has been adjusted and I've tried to clarify the docs a bit more. Also I've added more extensive content to the user guide.
