### ISSUE TITLE
Support for NUnit4

### ISSUE THREAD

**Issue by drjameshouse** [xmlunit/xmlunit.net#40]
When updating to use NUnit 4.0.1 the following exception occurs:
System.TypeLoadException : Method 'get_Description' in type 'Org.XmlUnit.Constraints.CompareConstraint' from assembly 'xmlunit-nunit3-constraints, Version=2.9.2.240, Culture=neutral, PublicKeyToken=e7d7e3088fd452f6' does not have an implementation.

NUnit4 requires constraints to have a Description getter.

**Comment by bodewig** [comment]
I haven't even been aware there is an NUnit 4.x, yet. Thanks for the heads up. This should probably be listed as breaking change over at nunit.org.

**Comment by mingyaulee** [comment]
From what I understand, in NUnit3 it was a virtual property and now it is abstract. Can we just declare an override for the virtual Description property so that it will be compatible with NUnit4?

**Comment by bodewig** [comment]
sorry, I've pushed #41 to a branch a while ago and was distracted by the CI failing again, which ha become a real nuisance. Yes I believe that's all that is required, I'll try to push out a new release soonish.

**Comment by bodewig** [comment]
I've just published 2.10.0
