### ISSUE TITLE
Build should target appropriate framework (.NET 3.5)

### ISSUE THREAD

**Issue by joephayes** [xmlunit/xmlunit.net#7]
.NET 3.5 is the minimum required framework version (because of LINQ).  What does this mean for Mono? Is Mono 3.5 the equivalent framework?

Change NuGet package to deliver assemblies into appropriate framework folders.

**Comment by bodewig** [comment]
I wonder whether it isn't more appropriate to leave the nuget package as "framework independent", but must admit I haven't done much research on the implications.

**Comment by joephayes** [comment]
What I was really wanted to specify was .NET 3.5 or better (to ensure
System.Xml.Linq would be available)

**Comment by bodewig** [comment]
OK, if I read the nuget spec correctly we'd copy the assemblies to a net/35 folder and the matching logic of nuget would select that for everything >= 3.5.  Initially I was afraid we'd have to copy the same assembly to N folders.

**Comment by joephayes** [comment]
Good. That matches my understanding. In general, I see that libraries that
target multiple frameworks build binaries to multiple directories (one for
each targeted framework) and then the nuspec picks up the binaries from
each directory. For example,

<files>
    <file src="../build/net/bin/net35/xmlunit-core.dll"
target="lib/net35/xmlunit-core.dll"/>
    <file src="../build/net/bin/net40/xmlunit-core.dll"
target="lib/net40/xmlunit-core.dll"/>
    <file src="../build/net/bin/net45/xmlunit-core.dll"
target="lib/net45/xmlunit-core.dll"/>
  </files>

This seems to cover the Windows/.NET side. What I don't know is how Mono
works into the mix and how it reacts to nuget packages that target specific
frameworks.

The best way, I think is to simply run some experiments and see what
happens with Mono on Linux.

J
